/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedStartingBalanceRouteImport } from './routes/_authenticated/starting-balance'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMutationsRouteImport } from './routes/_authenticated/mutations'
import { Route as AuthenticatedIncomeRouteImport } from './routes/_authenticated/income'
import { Route as AuthenticatedExpenseRouteImport } from './routes/_authenticated/expense'
import { Route as AuthenticatedIncomeBreakdownRouteImport } from './routes/_authenticated/income_.breakdown'
import { Route as AuthenticatedExpenseBreakdownRouteImport } from './routes/_authenticated/expense_.breakdown'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStartingBalanceRoute =
  AuthenticatedStartingBalanceRouteImport.update({
    id: '/starting-balance',
    path: '/starting-balance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMutationsRoute = AuthenticatedMutationsRouteImport.update({
  id: '/mutations',
  path: '/mutations',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIncomeRoute = AuthenticatedIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExpenseRoute = AuthenticatedExpenseRouteImport.update({
  id: '/expense',
  path: '/expense',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIncomeBreakdownRoute =
  AuthenticatedIncomeBreakdownRouteImport.update({
    id: '/income_/breakdown',
    path: '/income/breakdown',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExpenseBreakdownRoute =
  AuthenticatedExpenseBreakdownRouteImport.update({
    id: '/expense_/breakdown',
    path: '/expense/breakdown',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/expense': typeof AuthenticatedExpenseRoute
  '/income': typeof AuthenticatedIncomeRoute
  '/mutations': typeof AuthenticatedMutationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/starting-balance': typeof AuthenticatedStartingBalanceRoute
  '/': typeof AuthenticatedIndexRoute
  '/expense/breakdown': typeof AuthenticatedExpenseBreakdownRoute
  '/income/breakdown': typeof AuthenticatedIncomeBreakdownRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/expense': typeof AuthenticatedExpenseRoute
  '/income': typeof AuthenticatedIncomeRoute
  '/mutations': typeof AuthenticatedMutationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/starting-balance': typeof AuthenticatedStartingBalanceRoute
  '/': typeof AuthenticatedIndexRoute
  '/expense/breakdown': typeof AuthenticatedExpenseBreakdownRoute
  '/income/breakdown': typeof AuthenticatedIncomeBreakdownRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/_authenticated/expense': typeof AuthenticatedExpenseRoute
  '/_authenticated/income': typeof AuthenticatedIncomeRoute
  '/_authenticated/mutations': typeof AuthenticatedMutationsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/starting-balance': typeof AuthenticatedStartingBalanceRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/expense_/breakdown': typeof AuthenticatedExpenseBreakdownRoute
  '/_authenticated/income_/breakdown': typeof AuthenticatedIncomeBreakdownRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/login'
    | '/expense'
    | '/income'
    | '/mutations'
    | '/settings'
    | '/starting-balance'
    | '/'
    | '/expense/breakdown'
    | '/income/breakdown'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/login'
    | '/expense'
    | '/income'
    | '/mutations'
    | '/settings'
    | '/starting-balance'
    | '/'
    | '/expense/breakdown'
    | '/income/breakdown'
  id:
    | '__root__'
    | '/_authenticated'
    | '/dashboard'
    | '/login'
    | '/_authenticated/expense'
    | '/_authenticated/income'
    | '/_authenticated/mutations'
    | '/_authenticated/settings'
    | '/_authenticated/starting-balance'
    | '/_authenticated/'
    | '/_authenticated/expense_/breakdown'
    | '/_authenticated/income_/breakdown'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/starting-balance': {
      id: '/_authenticated/starting-balance'
      path: '/starting-balance'
      fullPath: '/starting-balance'
      preLoaderRoute: typeof AuthenticatedStartingBalanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mutations': {
      id: '/_authenticated/mutations'
      path: '/mutations'
      fullPath: '/mutations'
      preLoaderRoute: typeof AuthenticatedMutationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/income': {
      id: '/_authenticated/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof AuthenticatedIncomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expense': {
      id: '/_authenticated/expense'
      path: '/expense'
      fullPath: '/expense'
      preLoaderRoute: typeof AuthenticatedExpenseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/income_/breakdown': {
      id: '/_authenticated/income_/breakdown'
      path: '/income/breakdown'
      fullPath: '/income/breakdown'
      preLoaderRoute: typeof AuthenticatedIncomeBreakdownRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expense_/breakdown': {
      id: '/_authenticated/expense_/breakdown'
      path: '/expense/breakdown'
      fullPath: '/expense/breakdown'
      preLoaderRoute: typeof AuthenticatedExpenseBreakdownRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedExpenseRoute: typeof AuthenticatedExpenseRoute
  AuthenticatedIncomeRoute: typeof AuthenticatedIncomeRoute
  AuthenticatedMutationsRoute: typeof AuthenticatedMutationsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStartingBalanceRoute: typeof AuthenticatedStartingBalanceRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedExpenseBreakdownRoute: typeof AuthenticatedExpenseBreakdownRoute
  AuthenticatedIncomeBreakdownRoute: typeof AuthenticatedIncomeBreakdownRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedExpenseRoute: AuthenticatedExpenseRoute,
  AuthenticatedIncomeRoute: AuthenticatedIncomeRoute,
  AuthenticatedMutationsRoute: AuthenticatedMutationsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStartingBalanceRoute: AuthenticatedStartingBalanceRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedExpenseBreakdownRoute: AuthenticatedExpenseBreakdownRoute,
  AuthenticatedIncomeBreakdownRoute: AuthenticatedIncomeBreakdownRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
